steps:
  - name: node:13.5
    entrypoint: yarn
    args: ['install']
  - name: node:13.5
    entrypoint: yarn
    args: ['build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/nginx", "-f", "Dockerfile", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/nginx"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'marunouchi-lunch', '--image', 'gcr.io/$_PROJECT_ID/nginx', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--concurrency=5']
images:
  - gcr.io/$_PROJECT_ID/nginx
